const data_funcionarios = [ 
   {
       nome:"Renato da silva",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"img.jpg",
       modulo: "M1",
       ativo: true,
   },
   {
       nome:"João Roberto",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"face.png",
       modulo: "M1",
       ativo: false,
   },
   {
       nome:"Renata da Silva",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"face1.jpeg",
       modulo: "M2",
       ativo: true,
   },
   {
       nome:"Bruno",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"face2.jpeg",
       modulo: "M3",
       ativo: false,
   },
   {
       nome:"Mariana",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"face3.jpeg",
       modulo: "M4",
       ativo: false,
   },
   {
       nome:"Ana Maria",
       cargo:"Facilitador - M2",
       empresa:"Kenzie Academy",
       image:"face4.jpg",
       modulo: "M2",
       ativo: true,
   },
   {
       nome:"Natalia",
       cargo:"Facilitador - M2",
       empresa:"Kenzie Academy",
       image:"face5.jpeg",
       modulo: "M2",
       ativo: true,
   },
   {
       nome:"Caio",
       cargo:"Facilitador - M2",
       empresa:"Kenzie Academy",
       image:"face5.jpg",
       modulo: "M2",
       ativo: false,
   },
   {
       nome:"Renata da Silva",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"face1.jpeg",
       modulo: "M2",
       ativo: true,
   },
   {
       nome:"Bruno",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"face2.jpeg",
       modulo: "M3",
       ativo: false,
   },
   {
       nome:"Mariana",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"face3.jpeg",
       modulo: "M4",
       ativo: false,
   },
   {
       nome:"Ana Maria",
       cargo:"Facilitador - M2",
       empresa:"Kenzie Academy",
       image:"face4.jpg",
       modulo: "M2",
       ativo: true,
   },
   {
       nome:"Natalia",
       cargo:"Facilitador - M2",
       empresa:"Kenzie Academy",
       image:"face5.jpeg",
       modulo: "M2",
       ativo: true,
   },
   {
       nome:"Caio",
       cargo:"Facilitador - M2",
       empresa:"Kenzie Academy",
       image:"face5.jpg",
       modulo: "M2",
       ativo: false,
   },
]