const data_funcionarios = [ 
   {
       nome:"Renato da silva",
       cargo:"Instrutor",
       empresa:"Kenzie Academy",
       image:"img.jpg",
       modulo: "M1",
       ativo: true,
       salario:1000,
       tempoEmpresa:3,
   },
   {
       nome:"João Roberto",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"face.png",
       modulo: "M1",
       ativo: false,
       salario:1500,
       tempoEmpresa:1,
   },
   {
       nome:"Renata da Silva",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"face1.jpeg",
       modulo: "M2",
       ativo: true,
       salario:3000,
       tempoEmpresa:3,
   },
   {
       nome:"Bruno",
       cargo:"Instrutor",
       empresa:"Kenzie Academy",
       image:"face2.jpeg",
       modulo: "M3",
       ativo: false,
       salario:1200,
       tempoEmpresa:3,
   },
   {
       nome:"Mariana",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"face3.jpeg",
       modulo: "M4",
       ativo: false,
       salario:1500,
       tempoEmpresa:3,
   },
   {
       nome:"Ana Maria",
       cargo:"Facilitador - M2",
       empresa:"Kenzie Academy",
       image:"face4.jpg",
       modulo: "M2",
       ativo: true,
       salario:1500,
       tempoEmpresa:1,
   },
   {
       nome:"Natalia",
       cargo:"Facilitador - M2",
       empresa:"Kenzie Academy",
       image:"face5.jpeg",
       modulo: "M2",
       ativo: true,
       salario:1200,
       tempoEmpresa:1,
   },
   {
       nome:"Caio",
       cargo:"Facilitador - M2",
       empresa:"Kenzie Academy",
       image:"face5.jpg",
       modulo: "M2",
       ativo: false,
       salario:1200,
       tempoEmpresa:4,
   },
   {
       nome:"Renata da Silva",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"face1.jpeg",
       modulo: "M2",
       ativo: true,
       salario:1200,
       tempoEmpresa:6,
   },
   {
       nome:"Bruno",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"face2.jpeg",
       modulo: "M3",
       ativo: false,
       salario:1300,
       tempoEmpresa:6,
   },
   {
       nome:"Mariana",
       cargo:"Facilitador",
       empresa:"Kenzie Academy",
       image:"face3.jpeg",
       modulo: "M4",
       ativo: false,
       salario:1400,
       tempoEmpresa:3,
   },
   {
       nome:"Ana Maria",
       cargo:"Facilitador - M2",
       empresa:"Kenzie Academy",
       image:"face4.jpg",
       modulo: "M2",
       ativo: true,
       salario:1400,
       tempoEmpresa:3,
   },
   {
       nome:"Natalia",
       cargo:"Instrutor - M2",
       empresa:"Kenzie Academy",
       image:"face5.jpeg",
       modulo: "M2",
       ativo: true,
       salario:3000,
       tempoEmpresa:3,
   },
   {
       nome:"Caio",
       cargo:"Facilitador - M2",
       empresa:"Kenzie Academy",
       image:"face5.jpg",
       modulo: "M2",
       ativo: false,
       salario:3000,
       tempoEmpresa:3,
   },
]